yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'


urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
import debug_toolbar

from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied_view'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField(max_length=400)

    def __str__(self):
        return self.title


class Post(CreatedModel):
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        unique_together = ['user', 'author']

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        labels = {
            'text': 'Текст поста',
            'group': 'Группа',
            'image': 'Изображение'
        }
        help_texts = {'text': 'Текст нового поста',
                      'group': 'Выберите группу'}
        fields = ['text', 'group', 'image']


class PostFormEdit(forms.ModelForm):
    class Meta:
        model = Post
        labels = {
            'text': 'Текст поста',
            'group': 'Группа',
            'image': 'Изображение'
        }
        help_texts = {'text': 'Текст редактируемого поста',
                      'group': 'Группа, к которой относится пост'}
        fields = ['text', 'group', 'image']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.core.paginator import Paginator

from .models import Post, Group, User, Follow
from .forms import PostForm, PostFormEdit, CommentForm


def authorized_only(func):
    def check_user(request, *args, **kwargs):
        if request.user.is_authenticated:
            return func(request, *args, **kwargs)
        return redirect('/auth/login/')
    return check_user


def piginator(request, post):
    paginator = Paginator(post, settings.NUMBER_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


@cache_page(20)
def index(request):
    template = 'posts/index.html'
    posts = Post.objects.select_related('author', 'group').all()
    return render(request, template, {'page_obj': piginator(request, posts)})


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    context = {
        'page_obj': piginator(request, posts),
        'group': group,
    }
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    user = request.user
    template = 'posts/profile.html'
    posts = author.posts.all()
    if request.user.is_authenticated:
        following = Follow.objects.filter(user=user, author=author).exists()
    else:
        following = False
    context = {
        'author': author,
        'user': user,
        'page_obj': piginator(request, posts),
        'count': posts.count(),
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    one_post = get_object_or_404(Post, id=post_id)
    comments = one_post.comments.all()
    form = CommentForm()
    context = {
        'one_post': one_post,
        'form': form,
        'comments': comments
    }
    return render(request, template, context)


@authorized_only
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', username=request.user.username)
        return render(request, 'posts/create_post.html', {'form': form})
    return render(request, 'posts/create_post.html', {'form': form})


def post_edit(request, post_id):
    one_post = get_object_or_404(Post, id=post_id)
    if request.user != one_post.author:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostFormEdit(
        request.POST or None,
        instance=one_post,
        files=request.FILES or None,
    )
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('posts:post_detail', post_id=post_id)
    return render(request, 'posts/create_post.html',
                  {'form': form, 'is_edit': True, 'post_id': post_id})


@authorized_only
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@authorized_only
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    template = 'posts/follow.html'
    title = 'Посты ваших любимых авторов'
    context = {
        'title': title,
        'page_obj': piginator(request, posts),
    }
    return render(request, template, context)


@authorized_only
def profile_follow(request, username):
    user = request.user
    author = User.objects.get(username=username)
    if author != user:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect('posts:profile', username=username)


@authorized_only
def profile_unfollow(request, username):
    author = User.objects.get(username=username)
    following = Follow.objects.filter(user=request.user, author=author)
    following.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title%}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %}  
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать запись
          {% else %}
            Добавить запись
          {% endif %}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                {{field.label}}: {{ error|escape }}
              {% endfor %}
            {% endfor %}
          {% endif %}
        </div>
        <div class="card-body">
        {% if is_edit %}
          <form method="post" action="{% url 'posts:post_edit' post_id %}">
        {% else %}
          <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create' %}">
        {% endif %}    
            {% csrf_token %} 
            {% for field in form %}
              <div class="form-group row my-3 p-3" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                <label class="col-md-3 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                  <div class="col-md-6">
                    {{ field }}
                    {% if field.help_text %}
                      <p><small class="form-text text-muted">{{ field.help_text|safe }}</small></p>
                    {% endif %}
                  </div>
              </div>
            {% endfor %}
            <div class="d-flex justify-content-end">              
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load static %}
{% block header %}Новостная лента{% endblock %}
{% block content %}
  <h5>{{ title }}</h5>
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'includes/article.html' %}
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">
        все записи группы</a>
    {% else %}
      <a href="">...</a>   
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
 {{ group.title }}
{% endblock %}
{% block header %}{{ group.title }}{% endblock %}
{% block content %}
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
    {% include 'includes/article.html' %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}
 

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{% block header %}Главная страница{% endblock %}
{% block content %}
  <h5>Последние обновления на сайте</h5>
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'includes/article.html' %}
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">
        все записи группы</a>
    {% else %}
      <a href="">...</a>   
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title%}
  Пост {{ one_post.text|truncatechars:30 }}
{% endblock %}
{% block header %}Подробнее о посте №{{ one_post.pk }}{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ one_post.pub_date|date:"d E Y" }} 
        </li>
        {% if one_post.group %}       
          <li class="list-group-item">
            Группа: {{ one_post.group }}
            <a href="{% url 'posts:group_list' one_post.group.slug %}">
              все записи группы
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ one_post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{one_post.author.posts.count}}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' one_post.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail one_post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ one_post.text }}
      </p>
      {% if user == one_post.author %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' one_post.pk %}">
          редактировать запись
        </a>
      {% endif %}
      {% include 'includes/comment.html' %}
    </article>
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title%}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
  <div class="mb-5">
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ count }}</h3>
    {% if user != author and user.is_authenticated %}
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
      {% endif %}
    {% endif %}
  </div>
  {% for post in page_obj %}
    {% include 'includes/article.html' %}
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">
        все записи группы</a>
    {% else %}
      <a href="">...</a>   
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}       
  {% include 'posts/includes/paginator.html' %}  
{% endblock %}